config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :restaurants do
    resources :comments
    resources :dishes do
      resources :reviews
    end
  end 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :find_restaurant

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.restaurant_id = @restaurant.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if @comment.update(comment_params)
      redirect_to restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def find_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :date)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@restaurant, @restaurant.comments.build]) do |form| %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-comment-form">

		<h1>Edit Comment</h1>

		<%= simple_form_for([@restaurant, @comment]) do |form| %>
			<div class="field">
            <%= form.label :body %>
            <%= form.text_area :body %>
            </div>

            <div class="field">
                <%= form.label :date %>
                <%= form.date_select :date %>
            </div>

            <div class="actions">
                <%= form.submit %>
            </div>
		<% end %>	

	</div>

</div>

<%= link_to 'Back', root_path %>

app/views/comments/new.html.erb
<div class="title-container">
    <h1>New Comment</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', restaurant_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Date:</strong>
  <%= @comment.date %>
</p>

<%= link_to 'Edit', edit_restaurant_comment_path(@comment) %> |
<%= link_to 'Back', restaurant_comments_path %>