config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :restaurants do
    resources :comments
    resources :dishes do
      resources :reviews
    end
  end 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :users
    has_many :dishes
    belongs_to :restaurants
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:price, :payment, :delivery_address, :delivery_time, :status, :notes)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :payment %>
    <%= form.text_field :payment %>
  </div>

  <div class="field">
    <%= form.label :delivery_address %>
    <%= form.text_field :delivery_address %>
  </div>

  <div class="field">
    <%= form.label :delivery_time %>
    <%= form.time_select :delivery_time %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>


<div class="title-container">
  <h1>Ordenes</h1>
  <%= link_to "Nueva Orden", new_order_path, class: "btn btn-default"%>
</div>

<div class="restaurants">
  <% @orders.each do |order| %>
    <div class="restaurant">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to truncate(order.delivery_address), order_path(order)%></h3>
          <p><%= truncate(order.notes, lenght: 150)%></p>
          <p><%= truncate(order.payment)%></p>
          <p><%= order.price%></p>
          <p><%= order.delivery_time%></p>
          <p>
            <%= link_to "Edit", edit_order_path(order), class: "btn btn-default"%>
            <%= link_to "Delete", order_path(order), data: {confirm: "Seguro que quieres eliminar la orden: #{order} ?", 
            }, method: :delete %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="title-container">
    <h1>New Order</h1>
</div>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @order.payment %>
</p>

<p>
  <strong>Delivery address:</strong>
  <%= @order.delivery_address %>
</p>

<p>
  <strong>Delivery time:</strong>
  <%= @order.delivery_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @order.notes %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>