config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :restaurants do
    resources :comments
    resources :dishes do
      resources :reviews
    end
  end 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/dish.rb
class Dish < ApplicationRecord
    belongs_to :restaurant
    has_many :reviews
    accepts_nested_attributes_for :reviews
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action :find_restaurant

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)
    @dish.restaurant_id = @restaurant.id

    if @dish.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    if @dish.update(dish_params)
      redirect_to restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    def find_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end 
    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :price, :description, :quantity, :rating)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= simple_form_for([@restaurant, @restaurant.dishes.build]) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-dish-form">

		<h1>Edit Dish</h1>

		<%= simple_form_for([@restaurant, @dish]) do |form| %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
        
          <div class="field">
            <%= form.label :price %>
            <%= form.text_field :price %>
          </div>
        
          <div class="field">
            <%= form.label :description %>
            <%= form.text_area :description %>
          </div>
        
          <div class="field">
            <%= form.label :quantity %>
            <%= form.number_field :quantity %>
          </div>
        
          <div class="field">
            <%= form.label :rating %>
            <%= form.text_field :rating %>
          </div>
        
          <div class="actions">
            <%= form.submit %>
          </div>
		<% end %>	
	</div>
</div>
<%= link_to 'Back', root_path %>

app/views/dishes/new.html.erb
<div class="title-container">
    <h1>New Dish</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', restaurant_dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Nuevo Review", new_restaurant_dish_review_path(@restaurant, @dish), class: "btn btn-default"%>
<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @dish.quantity %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @dish.rating %>
</p>

<%= link_to 'Back', root_path %>

<div class="restaurants">
  <% Review.all.each do |review| %>
    <div class="restaurant">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to truncate(review.body), restaurant_dish_review_path(@restaurant, @dish, review)%></h3>
          <p><%= truncate(review.value, lenght: 150)%></p>
          <p>
            <%= link_to "Edit", edit_restaurant_dish_review_path(@restaurant, @dish, review), class: "btn btn-default"%>
            <%= link_to "Delete", restaurant_dish_review_path(@restaurant, @dish, review), data: {confirm: "Seguro que quieres eliminar el comentario: #{review.body} ?", 
            }, method: :delete %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>