config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :restaurants do
    resources :comments
    resources :dishes do
      resources :reviews
    end
  end 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :dishes
    has_many :comments
    has_many :orders
    belongs_to :user 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @restaurant.dishes.build.reviews.build
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id

    if @restaurant.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path
    else
      render 'edit'
    end
    
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :mail, :address, :rating, :phone, 
        :dishes_attributes => [:name, :price, :description, :quantity, :rating, :reviews_attributes => [:body]])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title-container">
  <h1>Restaurants</h1>
  <%= link_to "Nuevo Restaurante", new_restaurant_path, class: "btn btn-default"%>
</div>

<div class="restaurants">
  <% @restaurants.each do |restaurant| %>
    <div class="restaurant">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to truncate(restaurant.name), restaurant_path(restaurant)%></h3>
          <p><%= truncate(restaurant.address, lenght: 150)%></p>
          <p>
          <% if current_user.id == restaurant.user_id%>
            <%= link_to "Edit", edit_restaurant_path(restaurant), class: "btn btn-default"%>
            <%= link_to "Delete", restaurant_path(restaurant), data: {confirm: "Seguro que quieres eliminar el restaurant: #{restaurant.name} ?", 
            }, method: :delete %>
            <%end%>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="title-container">
    <h1>New Restaurant</h1>
</div>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="title-container">
<h1>Bienvenido a <%=@restaurant.name%></h1>
<% if user_signed_in? %>
  <% if current_user.id == @restaurant.user_id %>
    <%= link_to "Nuevo Plato", new_restaurant_dish_path(@restaurant), class: "btn btn-default" %>
  <% end %>
  <%= link_to "Nuevo Comentario", new_restaurant_comment_path(@restaurant), class: "btn btn-default"%>
<% end %>
</div>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @restaurant.mail %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<%= link_to 'Back', restaurants_path %>

<div class="restaurants">
  <% Dish.all.each do |dish| %>

    <% if dish.restaurant_id == @restaurant.id%>
      <div class="restaurant">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= link_to truncate(dish.name), restaurant_dish_path(@restaurant, dish)%></h3>
            <p><%= truncate(dish.description, lenght: 150)%></p>
            <p><%= dish.price%></p>
            <p>
            <%if user_signed_in?%>
              <% if current_user.id == @restaurant.user_id%>
                <%= link_to "Edit", edit_restaurant_dish_path(@restaurant, dish), class: "btn btn-default"%>
                <%= link_to "Delete", restaurant_dish_path(@restaurant, dish), data: {confirm: "Seguro que quieres eliminar el plato: #{dish.name} ?", 
                }, method: :delete %>
              </p>
              <%end%>
            <%end%>
            
          </div>
        </div>
      </div>
    <% end%>
  <% end %>
</div>

<div class="restaurants">
  <% Comment.all.each do |comment| %> 
    <% if comment.restaurant_id == @restaurant.id%>
      <div class="restaurant">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= comment.body%></h3>
            <p><%= comment.date%></p>
            <p>
            <%if user_signed_in?%>
              <% if current_user.id == @restaurant.user_id%>
                <%= link_to "Edit", edit_restaurant_comment_path(@restaurant, comment), class: "btn btn-default"%>
                <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), data: {confirm: "Seguro que quieres eliminar el comentario: #{comment} ?", 
                }, method: :delete %>
              <% end%> 
            <% end%>                
            </p>
          </div>
        </div>
      </div>
    <% end%>
  <% end %>
</div>